version: '3.8'

services:
  app:
    build: .
    container_name: todolist_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # Montar el código para desarrollo en caliente

  db:
    image: mysql:8.0
    container_name: todolist_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist_user
      MYSQL_PASSWORD: todolist_password
    ports:
      - "3307:3307" #cambiado por conflicto con local devel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


